trigger:
- main

pool:
  name: 'Default'

variables:
- group: Finance-secrets  # <--- Change this line here

steps:
- script: |
    # This maps the Library secret to an Environment Variable for Ansible
    export DB_PASSWORD=$(DB_PASSWORD) 
    ansible-playbook -i ansible/inventory.ini ansible/site.yml
  displayName: 'Run Ansible Deployment'
  env:
    DB_PASSWORD: $(DB_PASSWORD)